### ISSUE TITLE
Анализируй это!

### ISSUE THREAD

**Issue by Brain89** [rambler-ios/team#101]
Доклад посвящён наиболее популярным статическим анализаторам кода для iOS. Будет рассказано, как ими пользоваться, какие проблемы они решают, как внедрить их в ваш привычный цикл разработки, как писать для них свои правила. Плюс к этому поделимся своим опытом интеграции статического анализа и CI.
После доклада слушатели, ещё не успевшие плотно поработать со статическими анализаторами кода, смогут быстро к этому приступить.

**Comment by etolstoy** [comment]
> наиболее популярным статическим анализаторам

про SwiftLint будет?

**Comment by serkrapiv** [comment]
нет

2017-05-11 18:43 GMT+03:00 Egor Tolstoy <notifications@github.com>:

**Comment by aknew** [comment]
Добрый день.
Подскажите, будет ли в докладе рассмотрен вопрос взаимодействия анализаторов (конкретно пункта analyze он же clang-analyzer, но и про другие интересно) c Typhoon и DI в целом? Похоже, что clang-analyzer попросту не находит связи между классами из-за DI и у него не получается их анализировать, в целом он так же ведет себя если вообще не присваивать объекты и только дергать у него методы/свойства.
С уважением.
ПС хотел накидать простенький пример для иллюстрации, но столкнулся с тем что Xcode перестал ходить внутрь других фаилов при анализе вообще, как с этим бороться не знаю пока, а без этого пример не очень-то информативен.

**Comment by serkrapiv** [comment]
Интересно, пока рассматривать не планировали. Было бы здорово посмотреть на пример если будет возможность

**Comment by aknew** [comment]
Жаль то этот не рассматривается
Пример выложил на [гуглдрайв](https://drive.google.com/open?id=0B3uPq-kBb6HhdTB4TDIyakl1VTA ) , там готовый проект с подключенным тайфуном и куча вариантов вызова одной и той же функции с по-разному задекламированным/присвоенным свойством (как именно задается через #define CASE N в хедере) чтоб посмотреть поймает ли анализатор деление на нуль, что я получаю в том или ином случае там тоже есть (и это меня смущает - я практически уверен что полгода назад в подобных ситуациях поведение было другим)

**Comment by serkrapiv** [comment]
Спасибо, покопался сам ещё. Получается даже при ручном задании зависимостей снаружи анализатор не видит ошибки. Нужно либо на месте классы создавать, либо определения классов держать в том же файле. И так и так тлен какой-то.

**Comment by Brain89** [comment]
Слайды - https://www.slideshare.net/Rambler-iOS/ss-76457847
