### ISSUE TITLE
Нужны ли бэкенд-разработчики, когда есть Swift

### ISSUE THREAD

**Issue by Brain89** [rambler-ios/team#103]
**Описание доклада**

> Любой iOS команде в повседневной практике требуется тот или иной вспомогательный инструментарий, оптимизирующий рутинные процессы. В рамках доклада посмотрим на Swift как на инструмент для реализации этих задач. На конкретном примере рассмотрим как развернуть Swift-окружение, чтобы писать серверный инструментарий.
> Изучим имеющиеся фреймворки и сравним лучший из них с популярными серверными платформами. 
> Также будут затронуты вопросы микросервисной архитектуры, проблемы и best practices в бэкенд-разработке.

**Comment by Brain89** [comment]
Слайды: https://www.slideshare.net/Rambler-iOS/swift-76456250

**Comment by AndreyZarembo** [comment]
Парни, привет! А есть текст доклада, по которому выступление было?

**Comment by AndreyZarembo** [comment]
А ещё, вы же выложите исходники сервера для Что Где Когда?  )

**Comment by smejl** [comment]
Привет. 
Исходники выложили месяца два назад. )
https://github.com/strongself/rambobot

Пока текста нет, может позже статью напишем.

**Comment by AndreyZarembo** [comment]
Спасибо!
