### ISSUE TITLE
Выступление на AppsConf: Чистая архитектура с VIPER

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#11]
На конференции AppsConf @serkrapiv  выступает с докладом [Чистая архитектура с VIPER](http://appsconf.ru/2016/abstracts/2090).

Тот же доклад, что и на CodeFest, с незначительными правками.

**Comment by x0000ff** [comment]
Реально ли найти видео этого выступления? Гугл не помог.

**Comment by etolstoy** [comment]
Насколько я знаю, CodeFest еще не публиковал видео, только слайды.

**Comment by serkrapiv** [comment]
@x0000ff На AppsConf выступление будет 31 мая, может быть там появится видео.

Организаторы CodeFest говорили, что видео появится примерно через 2 месяца после конференции, то есть в начале июня. Ждем-с.

**Comment by etolstoy** [comment]
Видео с CodeFest: https://www.youtube.com/watch?v=uS8zropcvdU
