### ISSUE TITLE
Обновляем список материала для ознакомления

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#12]
Сейчас у нас есть [список книг/статей/видео](https://confluence.rambler-co.ru/pages/viewpage.action?pageId=18746156), который мы раздаем всем новичкам в команде и тем, кто не прошел собеседование. Цель - направить человека на изучение требуемых для работы у нас областей, обеспечив его проверенным материалом.

Список составлялся нами с @Hastewave на скорую руку, и его явно можно сильно профильтровать и дополнить. Ваши предложения - в комментарии.

**Comment by complexityclass** [comment]
Я вот еще начал такой road map для начинающего разработчика заполнять, можно в него тоже дополнить кто что считает нужным (это пока еще далеко не законченный вариант)

https://coggle.it/diagram/V0BH1SQ4sVlKP8zj/4ae95a329615f6b74791353c42ed0f434ba35e182cda93f2c4f7e55b90b71af1

**Comment by etolstoy** [comment]
@complexityclass Выглядит круто, как доделаешь - сможем встроить.

Пока что тикет закрываю, перенес сюда старый список с Confluence - дальше будем работать через Pull Request'ы.

Ссылка: https://github.com/rambler-ios/team/blob/master/team/literature.md
