### ISSUE TITLE
Выступление на Rambler.iOS: Об электронной коммерции

### ISSUE THREAD

**Issue by Brain89** [rambler-ios/team#13]
Планируется рассказать об электронной коммерции в целом и о ее применении в мобильной мире в частности. 

Предварительно, доклад состоит из двух частей: общей, о теории электронной коммерции и интернет-эквайринга, и частной, о проведении платежей с помощью iOS-устройства. 

Докладчики: @Brain89 и @gookellas.
Описание доклада от @gookellas:

> В своем докладе я расскажу, что такое электронная коммерция и интернет-эквайринг в частности, а также почему это актуально. Будут рассмотрены основные участники и этапы обработки платежной транзакции, выполненной с помощью банковской карты в сети. Также коснемся вопросов защиты от мошенничества с данными банковских карт при помощи технологии 3-D Secure и узнаем, зачем проходить сертификацию PCI DSS. В конце поговорим про возможность осуществления оплаты банковскими картами в мобильных приложениях. 
> Доклад рассчитан на новичков, которые только начинают знакомиться с электронными платежами. 

Выступление планируется на **Rambler.iOS 7**

**Comment by etolstoy** [comment]
Выглядит очень интересно, нужно будет подумать о продолжительности доклада - стандартных 25 минут, видимо, не хватит.

**Comment by Brain89** [comment]
Мне кажется, можно две части сделать, в сумме будет 50 минут где-то.

**Comment by etolstoy** [comment]
@Brain89 Саша, ждем от тебя развернутые тезисы твоей части доклада в ближайшее время. Первый прогон с черновиком выступления нужно будет устроить где-то в середине июня. Получится?

**Comment by Brain89** [comment]
Да, пойдет.

**Comment by Brain89** [comment]
Тезисы ко второй части. 

> Доклад посвящен существующим возможностям приема банковских карт к оплате товаров и услуг в мобильных iOS-приложения. Будет дан обзор вариантов реализации от открытия встроенной веб-формы до point-to-point encryption и Apple Pay. Доклад рассчитан на программистов, мало знакомых со сферой электронной коммерции, но столкнувшихся в своих проектах с задачей приема платежей.

**Comment by etolstoy** [comment]
https://www.youtube.com/watch?v=14OR6yWevSU
https://www.youtube.com/watch?v=p4fIL1Pt5ck
