### ISSUE TITLE
Рассказ о тренинге для спикеров

### ISSUE THREAD

**Issue by DevAlloy** [rambler-ios/team#14]
21-22 числа проходил тренинг для спикеров. Впечатления о самого тренинга более чем хорошее, степень полезности - средняя. Готов сделать краткий пересказ с основными моментами.

**Comment by etolstoy** [comment]
Я за, жду подробностей, можно еще интерактивчика добавить :)

**Comment by serkrapiv** [comment]
Го в эту пятницу?
