### ISSUE TITLE
Flux, Redux, ReSwift

### ISSUE THREAD

**Issue by DevAlloy** [rambler-ios/team#17]
Интересно было бы послушать рассказ о ReSwift, Redux, Flux

**Comment by etolstoy** [comment]
@complexityclass, тут по твою душу запрос пришел.

**Comment by complexityclass** [comment]
Могу подготовиться за две недели и рассказать в одну из свободных пятниц

**Comment by etolstoy** [comment]
@complexityclass окей - заведу страницу с бронированием дат выступлений, определимся тогда.

**Comment by etolstoy** [comment]
@complexityclass можешь забивать свободные даты в [календаре](https://github.com/rambler-ios/team/blob/master/processes/weekly-meetings.md).
