### ISSUE TITLE
Рассказ о применении составных операций в SOA-проекте

### ISSUE THREAD

**Issue by novixon** [rambler-ios/team#18]
В последних спринтах на проекте "Рамблер/Почта" я занимался, в том числе, улучшением сетевого слоя приложения. Для этого был выбран подход "Compound operations" или "Составные операции", предложенный Apple на WWDC (Advanced NSOperations) и развитый ребятами из проекта Livejournal. 

На основе их опыта и собственного видения я создал компонент для удобной интеграции данного подхода в проект. В своём рассказе я затрону как тему конкретной реализации компонента (архитектурной и технической части), так и тему внедрения компонента в реальный проект (на примере Рамблер/Почты или Рамблер/Конференций).

Доклад запланирован на 17 июня.

**Comment by DevAlloy** [comment]
Не UX

**Comment by etolstoy** [comment]
@novixon можешь забивать свободные даты в [календаре](/processes/weekly-meetings.md).

**Comment by serkrapiv** [comment]
Эта штука наконец-то в поды вынесена?!

**Comment by igorJob93** [comment]
Материалы доклада будут опубликованы?
Планируете вынести этот компонент в открытый доступ, будут существенные отличия от текущей реализации в "Рамблер/Конференции" ?

**Comment by etolstoy** [comment]
@igorJob93 это выступление опебликовывать не будем - его нужно еще доработать до показа публике. Компонент будет разрабатываться в открытом доступе, можете следить за развитием в пока что пустом репозитории [COOperation](https://github.com/rambler-ios/COOperation). Отличия - да, будут 🙂.
