### ISSUE TITLE
Рассказ про Universal links

### ISSUE THREAD

**Issue by aporohov** [rambler-ios/team#21]
На WWDC 15 Apple представил новый подход к deep linking под названием Universal links. Рассказ про опыт внедрения Universal links на Афише. 

**Основные тезисы:**
1. Что это и зачем придумали
2. Схема работы
3. Как настроить у себя в проекте
4. Особенности реализации
6. Возникшие проблемы на Афише и как их решали

**Comment by etolstoy** [comment]
Отлично, забивай свободную дату: https://github.com/rambler-ios/team/blob/master/processes/weekly-meetings.md
