### ISSUE TITLE
Рассказ про Promises

### ISSUE THREAD

**Issue by DevAlloy** [rambler-ios/team#26]
Когда стоит применять, когда лучше воздержаться.

**Comment by mcrakhman** [comment]
Расскажу 5-го августа, тезисы будут чуть-позже 😃

**Comment by mcrakhman** [comment]
Итак, в ближайшую пятницу расскажу про promises.
Краткие тезисы:
- Что такое promises?
- Использование promises в iOS разработке (существующие библиотеки и подходы)
- Реализация promises библиотекой PromiseKit (основные методы, цепочки promises, обработка ошибок)
- Какие задачи можно решить с помощью promises, а какие - нельзя
- Использование promises на примере приложения: драм-машины с возможностью сохранять аудио-дорожки
- Подведение итогов: преимущества и недостатки
