### ISSUE TITLE
Обновить фото

### ISSUE THREAD

**Issue by AndreyZarembo** [rambler-ios/team#32]
По-моему уже пора )

**Comment by etolstoy** [comment]
Да, скоро будет :) Эта слишком пугает иностранных посетителей.

**Comment by skywinder** [comment]
хах, знакомые люди.
а это какого года фотка сейчас?

**Comment by etolstoy** [comment]
@skywinder Насколько я помню, начало 2016.

**Comment by skywinder** [comment]
`April 27, 2016 `  😉

**Comment by etolstoy** [comment]
Наконец-то обновили! :)

**Comment by skywinder** [comment]
🎉
