### ISSUE TITLE
Провести рассказ для дизайнеров по новым фичам iOS10

### ISSUE THREAD

**Issue by Hastewave** [rambler-ios/team#35]
Предварительно договорились на 30 июня 18:00 в Лектории.

Распределение тем:
- 228, 213 - 3d touch + расширения - Саша
- 216 - анимации и переходы - Ира
- 230 - CallKit - Саша
- 225 - Siri - Вадим
- 214 - Safari расширения - Андрей
- 240 - Proactive suggestions - Саша
- 222, 233, 236 - Apps Adaptive, new layout - Стас
- 223 - search api - Андрей
- Про часы - Ваня
- 204, 225 - imessage и стикеры - Миша Р
- 509 - speach kit - Стас
- 707, 708 - нотификации - Макс
- 724 - wide color + pdf - Миша Г

**Comment by etolstoy** [comment]
Плюс перед этим я расскажу о том, что было на WWDC:

Сейчас готово выступление со следующими разделами: 

- Организация конференции - что, как и где проходило
- Интересное для нас
- Другие конференции - AltConf, Cocoapods, etc.

Думаю, второй раздел не имеет особого смысла, учитывая что про все это мы будем рассказывать отдельно в подробностях. Предлагаю поступить так - буду вклиниваться в выступления ребят, если будет что дополнить по результатам общения с инженерами Apple.

**Comment by Sapozhnik** [comment]
@etolstoy, нет желания сделать запись? Не смогу присутствовать на встрече, но хотелось бы быть в курсе

**Comment by etolstoy** [comment]
@Sapozhnik Проблем нет - единственное, запись будет длинная :) Переговорка на 3 часа забронирована.

**Comment by etolstoy** [comment]
Неожиданно выступил со своим рассказом вчера, так что время отнимать не буду.
