### ISSUE TITLE
Тайм менеджмент для самых маленьких

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#39]
К одной из ближайших пятничных встреч я хочу подготовить небольшой рассказ о тайм менеджменте - что это такое, зачем это вообще нужно для разработчика и какие основные подходы встречаются.

Хаотичный набор тезисов:

- Тайм менеджмент - зачем он нужен
- Кратко о GTD
- Кратко об Agile Results
- Инструменты: Omnifocus, Evernote

**Comment by novixon** [comment]
Очень интересная тема. Еще можно про трекеры времени немного поговорить. 

Кстати, могу дополнить немного, рассказать про систему Любищева, так как недавно изучал: зачем можно логировать всё свое время и чего можно этим добиться.

**Comment by etolstoy** [comment]
Так, проапдейченный список тезисов:
- Зачем программисту нужен тайм-менеджмент
- Матрица Эйзенхауэра как самый простой способ приоритезации задачи
- Getting Things Done - основные принципы методологии
- Omnifocus - лучший инструмент для GTD
- Agile Results и его основные принципы
- Evernote и Agile Results

**Comment by iovannapopova** [comment]
По ссылке видео лекции Людвига Быстроновского «Интерес и важность»:
http://ludwigbistronovsky.ru/lectures/  
Посмотрите, они классные и полезные!

**Comment by DevAlloy** [comment]
https://ru.coursera.org/learn/learning-how-to-learn

**Comment by etolstoy** [comment]
GTD in 15 minutes: https://hamberg.no/gtd/
Agile Results Series: http://www.asianefficiency.com/task-management/agile-results-series-part-1-overview/
Review на книгу Mind for numbers (письменное изложение курса Learn how to learn): http://etolstoy.com/2016/02/16/mind-for-numbers-review/
