### ISSUE TITLE
Научиться автоматически обновлять release notes и скриншоты в сторе с помощью fastlane

### ISSUE THREAD

**Issue by serkrapiv** [rambler-ios/team#41]
На конфе MobileOptimized в Минске, которую я недавно посетил, один парень делал доклад про fastlane. И там он упомянул, что тулза deliver, входящая в fastlane, умеет автоматизировать процесс обновления метаданных в сторе. Больше всего интересуют скриншоты и release notes. Стоит покопать в этом направлении и прикрутить эту возможность нам.

Слайды презентации можно найти тут: https://speakerdeck.com/chipp/fastlane-beta-ili-pochiemu-ia-stal-pit-bol-shie-kofie

**Comment by serkrapiv** [comment]
@Beniamiiin говорят ты игрался с этой штукой?

**Comment by Beniamiiin** [comment]
@serkrapiv ну да, fastlane такое умеет, но сходу не скажу, как это сделать. Возьму эту задачу в работу, потом расскажу, что да как.

**Comment by Brain89** [comment]
Не нужно в рамках текущего процесса CD
