### ISSUE TITLE
Рассказать о том, как в LiveJournal устроена работа с лентами контента

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#45]
Тема организации лент с разными типами контента актуальна для многих наших приложений: Почты, Чемпионата, Афиши, да и многих других. В LiveJournal мы используем довольно интересное и легкорасширяемое решение. По результатам прошлого доклада Вадима, да и вообще, было несколько просьб раскрыть эту тему и рассказать о ней подробнее.

Короче, команда ЖЖ (@CognitiveDisson @juyka @constZinovyev ), поделитесь на одной из встреч знаниями об архитектурном устройстве наших лент, его плюсах и минусах.

**Comment by DevAlloy** [comment]
Я бы добавил сюда все интересные архитектурные проблемы/решения

**Comment by Brain89** [comment]
Меня еще интересуют следующие вопросы, которые хотелось бы в докладе увидеть или разобрать потом дополнительно. 

* Производительность (как и "долго ли" ищется место для вставки новой ячейки).
* Как синхронизируются анимационные транзакции, поступающие практически одновременно. Что, если они противоречат друг другу.
