### ISSUE TITLE
Deeplinking and Web to App traffic.

### ISSUE THREAD

**Issue by Zhukn1** [rambler-ios/team#46]
Всем привет!

Мне хотелось бы рассказать про диплинкинг, поделиться опытом и знаниями в формате дружеской встречи. 

Branch является международным лидером в этой области, SDK которого интегрирован в такие приложения как Twitter, Pinterest, Airbnb, Swarm и другие. Мы собрали очень много граблей и поэтому с удовольствием делимся опытом:)

Мне бы хотелось рассказать про то, какие существуют способы перетаскивания пользователей из мобильного веба в приложение и почему это важно. Покажу, что получается, а что не работает у крупных игроков.

### Тезисы

Краткий обзор о том, что такое диплинки и deffered deeplink.
Кейсы перемещения пользователей Web -> App.
Case studies от крупных приложений.
Идеи использования диплинков на примере приложений Rambler.

Если вам эта тема интересна или есть какая-нибудь текущая проблема (техническая или продуктовая), напишите, пожалуйста, чтобы я мог подробнее рассказать о том, как ее решить.

**Comment by DevAlloy** [comment]
Здорово! Лично мне было бы интересно послушать. А хочется выступить на Rambler.iOS, или зайти в гости на одну из наших пятничных встреч, где собирается только наша команда?

**Comment by Zhukn1** [comment]
я бы попробовал сначала только вашей команде рассказать и, если посчитаете что материал достоин Rambler.iOS, то тогда могу и там :)

**Comment by DevAlloy** [comment]
У нас уже было внутреннее выступление на эту тему. Перед Rambler.iOS мы гоняем выступления как внутренних, так и внешних докладчиков. Так что можно и без пятничной встречи. Обсудим в команде эту тему.

**Comment by etolstoy** [comment]
Я за пятничную встречу - в первую очередь доклад для команды, а там уже посмотрим :)

**Comment by etolstoy** [comment]
@Zhukn1 12 августа, 16 часов, подходит?

**Comment by Zhukn1** [comment]
@etolstoy не-а, к сожалению. 12 августа у меня д.р. и я буду в Калининграде. 13 прилетаю в Москву.

**Comment by etolstoy** [comment]
@Zhukn1 тогда выбирай любую свободную: https://github.com/rambler-ios/team/blob/master/processes/weekly-meetings.md

**Comment by Zhukn1** [comment]
@etolstoy 02.09.2016 будет отлично.
