### ISSUE TITLE
Implement ObjectIndexer component

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#49]
11 месяцев назад @CognitiveDisson в своей [статье про CoreSpotlight](https://habrahabr.ru/company/rambler-co/blog/268257/) пообещал, что в скором времени мы выпустим компонент, архитектуру которого он обрисовал. Потом Вадик перешел на ЖЖ, времени стало в разы меньше - и вот недавно мы об этом снова вспомнили. 

Сейчас я встраиваю интеграцию с CoreSpotlight в Рамблер.Конференции. После этого мы посмотрим на получившуюся систему и я вынесу ее в отдельный компонент.

**Comment by Brain89** [comment]
https://github.com/strongself/RamblerSpotlight
