### ISSUE TITLE
Рассказ о проблемах, встреченных при работе со Swift

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#5]
@complexityclass готовит рассказ о проблемах, с которыми он столкнулся при работе со swift и способах их решения.

Предварительная дата выступления: 20 мая.

**Comment by complexityclass** [comment]
_Расскажу о некоторых проблемах при разработке на Swift, а так же об общих впечатлениях от использования Swift  в продакшн и советах._

### Список тезисов:
* Build time. How to help teenager compiler.
* Swift is functional! Like Haskell, yep ?
* Generics are simple, I knew it from Java.
* Swift namespaces. Meh.
* Protocol-what programming ?
* Production ready? Why have you done this to me?!
* Live in Swift world.
