### ISSUE TITLE
Доклад про iOS Security

### ISSUE THREAD

**Issue by complexityclass** [rambler-ios/team#51]
Есть идея рассказать про безопасность, пока в голове такие направления докладов:
1. Общая информация про iOS security, sandboxing/keychain/touch id... (примерно по этому документу https://www.apple.com/business/docs/iOS_Security_Guide.pdf)
2. Небольшой обзор по pentesting или reverse engineering iOS приложений.
3. Доклад про Jailbreak и что с ним можно делать.

Что из этого могло бы быть интересно? Добавляйте свои предложения в комменты.

**Comment by Beniamiiin** [comment]
В принципе все интересно. В первую очередь хотелось бы послушать про JailBreak.

**Comment by etolstoy** [comment]
Я вообще за серию докладов, начиная с общей информации. Во второй теме можно небольшой воркшоп показать.

Лично мне сильно интересна тема реверсинга свифтовых приложений - на днях с наскока не справился.

**Comment by etolstoy** [comment]
@complexityclass Когда планируешь выступить?

**Comment by complexityclass** [comment]
@etolstoy хотел бы 23.09.16 по iOS Reverse Engineering

**Comment by etolstoy** [comment]
Отлично, забивай календарь.

**Comment by Brain89** [comment]
https://youtu.be/7xY7vdZrWRE
