### ISSUE TITLE
Запросы тем для еженедельных докладов

### ISSUE THREAD

**Issue by serkrapiv** [rambler-ios/team#56]
Пока что доклады у нас делаются по такому принципу: все шерстят в поисках чего-то интересного в своих проектах или делятся инфой по какой-то сторонней теме. Можно попробовать спрашивать народ о темах, о которых они хотели бы узнать, а затем отдавать кому-нибудь эту тему для подготовки доклада.

**Comment by etolstoy** [comment]
@serkrapiv предполагалось, что в таких случаях люди будут сюда issue закидывать. С промисами так было. Стоит, думаю, рассылку устроить на всех с предложением подумать или что-то такое.
