### ISSUE TITLE
Extend Your App With JavaScriptCore

### ISSUE THREAD

**Issue by mittsh** [rambler-ios/team#63]
### How to your productivity app extensible with JavaScriptCore?

Most applications (iOS, macOS) are limited by the set of features the developer implemented, but users often have more precise needs. We've made [Paw](https://paw.cloud/) extensible by exposing a JavaScript API so everyone can write plugins for their custom needs and share them on GitHub for the community. This talk will cover the basics of the JavaScriptCore's bindings between native code (Swift or ObjC) and JavaScript.

- Why we have decided to expose an extension API in Paw
- Benefits of making your app extensible
- Why JavaScript bindings over CocoaScript or Python
- Benefits of exposing a public API for your app
- Basics of JavaScriptCore, quick presentation of `JSValue`, `JSContext`, `JSExport`
- JavaScriptCore and multithreading
- Other tools using JavaScriptCore & Conclusion

![image](https://cloud.githubusercontent.com/assets/1319906/18738755/e6b870ac-809e-11e6-8dcf-b6ad51bfbc65.png)

**Comment by mittsh** [comment]
Looking forward to it tomorrow!!! 🇷🇺

**Comment by etolstoy** [comment]
@mittsh we too! :)
