### ISSUE TITLE
Функциональный лэйаут

### ISSUE THREAD

**Issue by Sapozhnik** [rambler-ios/team#74]
В одном прекрасном проекте случилась беда со скроллом ленты. Было решено отказаться от автолейаута в ячейках ленты. 
Появилась идея воспользоваться приемом из доклада "[Функциональный лэйаут](https://events.yandex.ru/lib/talks/3503/)".
Если вам интересно, могу рассказать с какими трудностями столкнулись, что из этого вышло и о впечатлениях от этого _достаточно спорного_ подхода. 

Отдельно можно будет подискутировать на тему "неоднозначных"  подходов.

**Comment by serkrapiv** [comment]
Да возгорится пламя.

**Comment by iovannapopova** [comment]
Да наконец-то!

**Comment by etolstoy** [comment]
Бронируй дату :)
