### ISSUE TITLE
Построение диаграмм UML

### ISSUE THREAD

**Issue by RinaRish** [rambler-ios/team#76]
При написании технической документации для проекта "Афиша" возникла идея добавить диаграммы UML. В своем докладе хочу осветить следующие вопросы:
1) Виды диаграмм и когда какую лучше использовать
2) Как диаграммы могут облегчить жизнь разработчику
3) Генерация диаграмм из кода
4) Сравнение тулзов (StarUML, Doxygen, GraphViz)

**Comment by DevAlloy** [comment]
Мне draw.io показался хорошим инструментом для построения диаграмм.
Тема интересная, я бы попросил вбросить побольше примеров из Афиши.
