### ISSUE TITLE
Swift performance

### ISSUE THREAD

**Issue by complexityclass** [rambler-ios/team#82]
Хочется сделать доклад про то, как писать производительный код на Swift
Вижу такие пункты :
-  ARC в Swift, отличия от ObjC, оптимизации
-  Runtime,  где проходит граница Swift/ObjC, как ее не рушить
-  Value/Reference типы, когда использовать и какие плюсы
-  Оптимизации на уровне SIL кода

Есть интерес к этой теме ?

**Comment by mcrakhman** [comment]
Йеп) Интерес есть, супер важная тема, как по мне. Было бы круто, если бы был какой-то пример, на котором разница в производительности между тем или иным подходом была бы очевидна.

**Comment by etolstoy** [comment]
Определенно интересно
