### ISSUE TITLE
Вопросы, задаваемые на собеседованиях

### ISSUE THREAD

**Issue by etolstoy** [rambler-ios/team#9]
Список тем, которые мы сейчас затрагиваем на собеседованиях я привел в [этом разделе](https://github.com/rambler-ios/team/blob/master/recruting.md). Сейчас я планирую подготовить опросник с перечислением всех тем, обязательных задач и вопросов - он поможет нам объективнее оценивать кандидатов, выставляя им баллы за каждый из разделов.

Так вот, давайте обсудим, какие темы помимо упомянутых стоит затрагивать.

**Comment by etolstoy** [comment]
Приведу текущий список сразу здесь:

Общие вопросы

Структуры данных, их отличие и области применения.
- Параллельное программирование. Основные понятия и простые задачи.
- Классические паттерны, определения и область применения.
- Принципы проектировния. SOLID, YAGNI, KISS, DRY.
- Основные подходы к архитектуре мобильных приложений.
- Unit-тестирование, TDD.

iOS

- Работа с памятью. ARC, MRC, weak/strong/assign/retain.
- Техники работы с многопоточностью. GCD, NSOperation.
- CoreData. Устройство, особенности и проблемы.
- Работа с runtime. Method swizzling, категории, dispatch tables.
- Работа с UI. Анимации, autolayout.

**Comment by serkrapiv** [comment]
При подготовке опросника, кстати, есть смысл по каждой теме ранжировать вопросы по сложности. Если кандидат, к примеру, на базовые вопросы по Core Data ответить не может, то к более сложным нет смысла переходить.

**Comment by etolstoy** [comment]
Обсуждали еще, что из этого можно опенсорсить. Я предлагаю следующее:

1. Выкладываем подробный список тем, о которых мы общаемся, с описанием того, на какие детали стоит обратить внимание.
2. Создаем форму в Google Forms, в которой по разделам заводим уже более подробные вопросы/подтемы/задачи. В этой же форме можно будет и выставлять результирующий балл для кадидата по каждой из тем.

**Comment by complexityclass** [comment]
Вместо параллельного многопоточное программирование
