### ISSUE TITLE
Путь к 100% краш фри

### ISSUE THREAD

**Issue by Sapozhnik** [rambler-ios/team#97]
Есть желание рассказать об интересном опыте, полученном при разработке Чемпионата. В целом, у всех проектов холдинга отличный краш фри, мне кажется, что стоит поделиться накопленными знаниями о том, как мы к этому пришли. 
Мы много рассказываем про отдельные этапы и техники, которые используем в разработке, я думаю, что стоит систематизировать все знания и показать, как они в комплексе влияют на конечный результат, а самое главное - техническое качество.
По моему мнению, высокий краш фри – один из главных показателей качества мобильного приложения, так как он отображает здоровье проекта в целом.
Думаю, что стоит кратко рассказать про важность, частые ошибки и, по нашему мнению, правильные техники в разработке мобильных приложений, а именно про:

- Архитектуру 
- Тесты 
- Валидацию данных
- Использование assert
- Постоянной поддержке старых версий приложения
- Особенности работы с пушами
- OCLint
- О чем стоит помнить при разработке, как заложиться на будущие изменения
- Отдельные советы, основанные на опыте, помогающие в разработке качественных продуктов

Это не финальные тезисы, а лишь набор идеи. Как думаете, стоит ли про это рассказать и, если стоит, то какие у вас есть идеи?

**Comment by DevAlloy** [comment]
Крашфри отображает примерно ничего. У Ресторанов нет и половины из перечисленного, при этом крашфри был под 100%.
Как сделать крашфри под 100%:
- Открываешь Fabric
- Берешь краш и решаешь его (повторить по кол-ву крешей)
- Профит

**Comment by Sapozhnik** [comment]
@serkrapiv, в следующий раз )
