### ISSUE TITLE
Прокачай свои навыки эффективности и креативности

### ISSUE THREAD

**Issue by RinaRish** [rambler-ios/team#98]
После просмотра курса Learning How to Learn: Powerful mental tools to help you master tough subjects и прочтения книги "Быстрый ум. Как забывать лишнее и помнить нужное" у меня возникло желания поделиться крутыми приемами, которые можно применять как в работе, так и в повседневной жизни. О чем расскажу в докладе:
1. Мозг с точки зрения физиологии. Как можно максимально использовать свои ресурсы.
2. Специальные приемы и техники, помогающие легко усваивать новое. 
3. Прокрастинация и вредные привычки
3. Паттерны повседневной жизни и креативность

**Comment by DevAlloy** [comment]
Хороший курс!
