### ISSUE TITLE
Тимбилдинг по коммуникациям

### ISSUE THREAD

**Issue by serkrapiv** [rambler-ios/team#99]
Моя девушка сейчас учится в Сколково, и недавно она расхваливала одно упражнение, которое у них было на одном из занятий. Говорит, что без спойлеров рассказать трудно, но суть в том, что участвующей команде нужно решить некую проблему. Описывается так: "Это упражнение на эффективную коммуникацию (навык слушать друг друга) и на организационные способности. Каждый член команды получает карточку с информацией, которая является частью большого целого. Для того, чтобы найти одно коллективное решение, нужно максимально эффективно общаться друг с другом".

Думаю, что мы можем попробовать эту историю в следующую пятницу, после чего отправиться в бар и укрепить результат =)

**Comment by Sapozhnik** [comment]
Хорошая идея! Но во время пятничных встреч у нас будет корпоратив. Может в четверг? Ну или до корпоратива в 15:00.

**Comment by serkrapiv** [comment]
@Sapozhnik Мне сообщили, что до 19:00 мы с корпоративом точно закончим. Поэтому, думаю, пятница в 19:00 вполне ок.
